#!/bin/sh

cd /usr/src/app

if [[ ! -e /installed ]]; then
    touch /installed
    
    echo "Not installed yet, run init scripts"
    
    echo "Database (ecto) create & migrate"
    mix ecto.create && mix ecto.migrate
    
    echo "Run tests"
    mix test
fi

exec mix phx.server "$@"
